resolver 127.0.0.11 valid=5s;

upstream rateguard_servers {
    zone rateguard 64k;
    server rateguard:8000 resolve;
}

server {
    listen 8000;

    location /check {
        proxy_pass http://rateguard_servers;
    }
}