upstream rateguard_servers {
    server host.docker.internal:8001;
    server host.docker.internal:8002;
}

server {
    listen 8000;

    location /check {
        proxy_pass http://rateguard_servers;
    }
}